### ISSUE TITLE
Support for OpenWrt 19.07.x

### ISSUE THREAD

**Issue by thecheatah** [firehol/packages#13]
Do the 18.06 packages support openwrt 19.07?

**Comment by philwhineray** [comment]
Sorry, I don't know the answer and I don't have access to a system to check at the moment (nor for several months at least).

**Comment by thecheatah** [comment]
Np, I was able to request a new package when OpenWrt went from 17.x to 18.x last time. Is it possible to produce a new build for 19.x without access to a system?

**Comment by philwhineray** [comment]
It should be possible on any reasonably up to date Linux with docker installed. The build downloads and uses the OpenWRT SDKs to cross-compile where necessary and make packages.

If you fancy giving it a go, you might get lucky with just replacing all `18.06` references in `build-openwrt.sh`. The download paths might need redoing a bit, if the libc's have changed.

If you can get it to build, I'll accept a PR. No need to maintain 18.06 support; if someone really wants that in the future, they can download the older packages.

**Comment by thecheatah** [comment]
@philwhineray Added pull request https://github.com/firehol/packages/pull/14

**Comment by philwhineray** [comment]
Looks like https://github.com/firehol/packages/releases/tag/2020-03-19-1724 is up. Thanks again for making the PR.

**Comment by thecheatah** [comment]
Np. Thanks for maintaining this package!

**Comment by thecheatah** [comment]
@philwhineray I have confirmed that the built package works in OpenWRT 19.07.2

**Comment by philwhineray** [comment]
Nice. Glad it worked for you and thanks for the heads up.
