### ISSUE TITLE
OpenWrt 23.x ipk

### ISSUE THREAD

**Issue by mrbluecoat** [firehol/packages#19]
Any ETA on an OpenWrt 23.x ipk? Or is OpenWrt no longer officially supported?

**Comment by philwhineray** [comment]
I don't have an openwrt system any longer, or the time to build packages
for new targets, but in theory you should be able to update the repo and
build your own if not too much has changed. Sorry to not be able to offer
more than that.

**Comment by mrbluecoat** [comment]
No worries @philwhineray , I'll just use https://github.com/openwrt/packages/blob/master/net/banip/files/README.md since they support the firehol feeds. Thanks.

**Comment by mrbluecoat** [comment]
P.S. You may want to update https://firehol.org/installing/openwrt/ to recommend https://openwrt.org/docs/guide-user/services/banip instead
