### ISSUE TITLE
opkg install

### ISSUE THREAD

**Issue by diazemiliano-zz** [firehol/packages#2]
Hi I've not understand if I `iprange_1.0.3-1_ar71xx_chaos_calmer.ipk` will work out of the box.
I can login to openwrt with `ssh` and next `wget` the `.ipk` file for install with `opkg`?
Thanks.

I would like to have a single dashboard with my multiple openwrt devices.

**Comment by philwhineray** [comment]
iprange does not provide a dashboard. Are you looking for netdata? There is no pre-built package for openwrt - someone would have to port it. You could probably install docker and follow the README to get a basic environment that can be used as a basis for doing so but I don't know how much effort it would be to produce and installable/runnable image.

As for iprange itself, if you have an ar71xx or brcm47xx device running chaos calmer, then yes, you should be able to do as you say, by using wget to obtain a `.ipk` file from the github releases area. If you have a different architecture it would need adding to the build scripts but that should not be too hard for me to arrange if you know what it is you need.

**Comment by diazemiliano-zz** [comment]
I'm sorry, I'll mix the repositories.
Im triying to use netdata.
Thanks anyway.
👍
