### ISSUE TITLE
Please Update Package Releases

### ISSUE THREAD

**Issue by sereeds** [firehol/packages#4]
Please create the latest packages for files at this location:
https://github.com/firehol/packages/releases/latest

I was specifically looking for the new netdata 1.9 for el7.centos.
The new features in 1.9 are amazing, great work.

**Comment by ktsaou** [comment]
@philwhineray how do we update netdata packages here?

**Comment by philwhineray** [comment]
Edit [package.conf](https://github.com/firehol/packages/blob/master/package.conf) and push it to github. If the travis build is OK, tag it and push the tag. The README has instructions.

If travis build fails, the scripts need fixing. I have never tested the `netdata` build by the way, which is why it is not mentioned in the README.

You can also build locally using docker, by following the readme.

**Comment by ktsaou** [comment]
did it, of course without reading the readme. Let me see if I can build it locally.

hm... the centos build fails. I think there was an issue with the spec file that is now fixed.
@philwhineray I haven't pushed the tags yet. 

Is there a way to build the latest git version of netdata or shall I release netdata 1.10 for this to be fixed?

**Comment by philwhineray** [comment]
The package.conf is used to locate a download mainly, and set up a few file names. I doubt it could pull from git as is but equally it would probably not be hard to add a bit of extra download logic.

**Comment by worldofpeace** [comment]
Um... releases maybe?

**Comment by sereeds** [comment]
Why is this closed?  the "latest release" still point to:
https://github.com/firehol/packages/releases/tag/2017-10-14-1440

https://github.com/firehol/packages/releases/latest

These are really handy packages for the RedHat/Centos etc.
Please update to the latest releases, netdata, firehol, iprange.

**Comment by worldofpeace** [comment]
It appears that the travis build failed and no one bothered to fix that or tag a commit?

**Comment by ktsaou** [comment]
I will release netdata v1.10 within the week. Please be patient...

**Comment by sereeds** [comment]
OK, no worries.  :-)
Your hard work is appreciated.
Thank you.
